name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      k8s-version:
        description: 'The kubernetes version to be used for building node image.'
        default: 'master'
        required: false
        type: string
  schedule:
    # Build the job every day for the master branch
    - cron: '0 9 * * *'
  push:
    branches: [ "main", 'v*.*.*' ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main", 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: quay.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: kviswana/kind-node


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set variables
        run: |
          KIND_VERSION=$(cat KIND_VERSION)
          BASE_IMAGE=$(cat BASE_IMAGE)
          echo "KIND_VERSION=$KIND_VERSION" >> $GITHUB_ENV
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_ENV
          export PATH=$PATH:$(go env GOPATH)/bin
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Build and install kind - ${{ env.KIND_VERSION }}
        run: |
          # The runner has kind pre-installed, removing the same to install the preferred version.
          rm -rf $(which kind)
          git clone --depth 1 --branch ${{ env.KIND_VERSION }} https://github.com/kubernetes-sigs/kind.git
          pushd kind
          git apply ../build-ppc64le.patch 
          popd

          make -C kind install

      - name: Build kind-node image - ${{ inputs.k8s-version }}
        run: |
          mkdir -p tmp/kubernetes
          git clone --single-branch --filter=tree:0 --branch ${{ inputs.k8s-version }} https://github.com/kubernetes/kubernetes tmp/kubernetes
          kind build node-image $PWD/tmp/kubernetes --arch ppc64le --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.k8s-version }} --base-image ${{ env.BASE_IMAGE }}

      - name: Publish node image
        if: github.event_name != 'pull_request'
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.k8s-version }}
