name: Build kind-node image for ppc64le

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: [ "v*.*.*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: quay.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: kviswana/kind-node


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set variables
        run: |
          KIND_VERSION=$(cat KIND_VERSION)
          BASE_IMAGE=$(cat BASE_IMAGE)
          KUBERNETES_VERSION=$(curl -Ls https://dl.k8s.io/release/stable.txt)
          echo "KIND_VERSION=$KIND_VERSION" >> $GITHUB_ENV
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_ENV
          echo "KUBERNETES_VERSION=$KUBERNETES_VERSION" >> $GITHUB_ENV

      - name: Build and install kind
        run: |
          # The runner has kind pre-installed, removing the same to download the preferred version.
          rm -rf $(which kind)
          echo $GOPATH
          git clone --depth 1 --branch ${{ env.KIND_VERSION }} https://github.com/kubernetes-sigs/kind.git
          pushd kind
          git apply ../build-ppc64le.patch 
          popd
          make -C kind install
          mv /home/runner/go/bin/kind /usr/local/bin/
          kind version

      - name: Build kind-node image - ${{ env.KUBERNETES_VERSION }}
        run: |
          mkdir -p tmp/kubernetes
          git clone --single-branch --filter=tree:0 --branch ${{ env.KUBERNETES_VERSION }} https://github.com/kubernetes/kubernetes tmp/kubernetes
          kind build node-image $PWD/tmp/kubernetes --arch ppc64le --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.KUBERNETES_VERSION}} --base-image ${{ env.BASE_IMAGE }}

      - name: Publish node image
        if: github.event_name != 'pull_request'
        run: |
          docker image tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.KUBERNETES_VERSION }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
